version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: spvr-nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/confs/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - spvr
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: spvr-php
    volumes:
      - ./:/var/www
    networks:
      - spvr
  supervisor:
    build:
      context: .
      dockerfile: ./docker/php/supervisor/Dockerfile
    container_name: spvr-supervisor
    volumes:
      - ./:/var/www
    networks:
      - spvr
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        TZ: "America/Sao_Paulo"
    volumes:
        - .docker-volumes/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
        - spvr

networks:
  spvr:
    name: "spvr"
